name: Publish Docker Hub

on:
  push:
    tags: [ '*.*.*.*' ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: parrazam/radicale-docker
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tag_names: true
        
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKERHUB_USERNAME }}
        pass: ${{ secrets.DOCKERHUB_TOKEN }}
        description: true
